#line 2 "src/c_lexer.yy.cpp"

#line 4 "src/c_lexer.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 91
#define YY_END_OF_BUFFER 92
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[246] =
    {   0,
        0,    0,   92,   90,    1,    2,   54,   90,   90,   51,
       57,   90,   41,   42,   49,   47,   38,   48,   36,   50,
       85,   85,   64,   39,   76,   65,   77,   63,   89,   89,
       43,   44,   59,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   45,   58,
       46,   60,    1,   79,    0,   83,    0,    0,   70,   55,
       71,    0,    0,   68,   52,   66,   53,   67,   37,    0,
       87,   69,   87,   84,    0,   85,    0,   85,   61,   80,
       78,   81,   62,   89,    0,    0,   73,   89,   89,   89,
       89,   89,   89,   26,   89,   89,   89,   89,   89,   89,

       23,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   72,   56,    0,   82,   40,    0,   87,    0,
       88,   87,   84,    0,   87,   86,   74,   75,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   27,
       89,    8,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,    0,    0,   87,
        0,    0,   87,   86,   11,   89,   33,    7,   89,   89,
       89,   89,   24,   22,   89,   89,   28,    5,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,    4,
       89,   89,    0,    0,   87,   29,   12,   89,   89,   89,

       89,    9,   89,   89,    6,   89,   89,   89,   89,   89,
       89,   21,   89,   89,   25,    0,    0,   89,   89,   10,
       13,   89,   31,   18,   35,   15,   19,   32,   89,   89,
       89,    0,    3,    0,   89,   34,   89,   20,   89,   89,
       30,   14,   17,   16,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   30,
       30,   30,   30,   30,   32,   30,   30,   33,   30,   30,
       34,   35,   36,   37,   30,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   30,   47,   48,   49,   50,
       51,   52,   30,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    5,
        5,    5,    5,    1,    1,    1,    1,    4,    4,    4,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[252] =
    {   0,
        0,    0,  386,  387,   64,  387,  361,   61,  380,  359,
       60,  347,  387,  387,  357,   56,  387,   57,   55,  356,
       80,   59,  387,  387,   62,  355,   64,  387,    0,   88,
      387,  387,  354,  321,  323,   65,   41,   45,   54,  324,
       71,  323,  331,   72,  312,  321,  319,  324,  387,   82,
      387,  387,  121,  387,  103,  387,  365,  100,  387,  387,
      387,  114,  123,  387,  387,  387,  387,  387,  387,  350,
      112,  387,  115,  133,  152,  128,    0,  160,  342,  387,
      387,  387,  341,    0,  135,  329,  387,  308,  320,  307,
      322,  309,  315,  301,  302,  299,  299,  302,  299,  296,

        0,  295,  299,   93,  297,  112,  109,  301,  294,  128,
      121,  299,  387,  387,  174,  387,  387,  181,  184,  191,
      387,  387,  186,  166,  179,  188,  387,  387,  293,  305,
      300,  288,  167,  302,  300,  296,  288,  294,  297,    0,
      283,    0,  289,  286,  275,  277,  279,  286,  272,  270,
      270,  282,  272,  276,  280,  282,  271,  312,  204,  209,
      219,  211,  221,  214,    0,  270,    0,    0,  261,  269,
      258,  265,    0,    0,  259,  256,    0,    0,  256,  256,
      253,  265,  255,  259,  256,  250,  240,  230,  235,    0,
      223,  234,  269,  228,  234,    0,    0,  224,  225,  230,

      221,    0,  213,  217,    0,  225,  218,  220,  204,  212,
      214,    0,  201,  203,    0,  237,  184,  181,  170,    0,
        0,  172,    0,    0,    0,    0,    0,    0,  153,  141,
      107,  203,  387,  252,  109,    0,   89,    0,   88,   35,
        0,    0,    0,    0,  387,  282,  287,  289,   67,  294,
      299
    } ;

static yyconst flex_int16_t yy_def[252] =
    {   0,
      245,    1,  245,  245,  245,  245,  245,  246,  245,  245,
      245,  247,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  248,  248,
      245,  245,  245,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  245,  245,
      245,  245,  245,  245,  246,  245,  246,  245,  245,  245,
      245,  247,  247,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  249,  245,  245,  245,
      245,  245,  245,  248,  246,  247,  245,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,

      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  249,  245,  245,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  245,  245,  245,
      245,  245,  245,  245,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  250,  245,  245,  248,  248,  248,  248,  248,

      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  250,  251,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  251,  245,  251,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,    0,  245,  245,  245,  245,  245,
      245
    } ;

static yyconst flex_int16_t yy_nxt[453] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       30,   29,   29,   31,    4,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   29,   41,   29,   42,   29,   29,
       29,   29,   43,   44,   45,   46,   47,   48,   29,   29,
       29,   49,   50,   51,   52,   53,   56,   53,   60,   65,
      126,   70,   67,   71,   71,   73,  244,   78,   78,   66,
       68,   69,   93,   61,   79,   80,   75,   82,   83,   76,
       76,   94,   95,   85,   96,   57,   73,   86,   74,   74,

       75,   98,   90,   97,   99,  113,   76,   75,   56,   91,
       76,   76,   77,  101,   76,   92,  105,  106,  115,  115,
      102,   75,   53,  116,   53,  245,  107,   76,  243,  108,
       71,   71,   62,  119,  119,   76,  144,   57,   77,  118,
       56,  242,  120,  121,  114,  122,  149,  145,   63,   73,
      241,   74,   74,  118,  240,  147,  120,  121,   76,   76,
       75,  150,  122,  123,  123,  124,  155,  124,  156,   57,
      125,  125,  148,  153,   75,   76,   73,  158,   78,   78,
      123,  154,  239,   76,  125,  125,  233,   75,  123,  234,
       76,   76,  115,  115,  159,  238,  159,  125,  125,  160,

      160,   75,  119,  119,  162,  233,  162,   76,  234,  163,
      163,  161,  121,  237,  122,   76,  123,  123,  164,  164,
      169,  170,  160,  160,  236,  161,  121,  160,  160,  163,
      163,  122,  194,  123,  194,  164,  235,  195,  195,  163,
      163,  123,  217,  164,  164,  164,  195,  195,  231,  121,
      230,  122,  195,  195,  233,  229,  228,  234,  227,  226,
      225,  164,  121,  121,  122,  224,  223,  222,  122,  164,
      221,  220,  219,  218,  217,  215,  121,  214,  213,  212,
      211,  122,   55,   55,   55,   55,   55,   62,   62,  210,
       62,   62,   84,   84,  216,  209,  216,  216,  216,  232,

      232,  232,  232,  232,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  196,  193,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      168,  167,  166,  165,  157,  152,  151,  146,  143,  142,
      141,  140,  139,  138,  137,  136,  135,  134,  133,  132,
      131,  130,  129,   63,  128,  127,  117,  245,  112,  111,
      110,  109,  104,  103,  100,   89,   88,   87,   81,   72,
       64,   63,   59,   58,   54,  245,    3,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245
    } ;

static yyconst flex_int16_t yy_chk[453] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    8,    5,   11,   16,
      249,   19,   18,   19,   19,   22,  240,   22,   22,   16,
       18,   18,   37,   11,   25,   25,   22,   27,   27,   22,
       22,   37,   38,   30,   38,    8,   21,   30,   21,   21,

       22,   39,   36,   38,   39,   50,   22,   21,   55,   36,
       21,   21,   21,   41,   22,   36,   44,   44,   58,   58,
       41,   21,   53,   62,   53,   63,   44,   21,  239,   44,
       71,   71,   63,   73,   73,   21,  104,   55,   21,   71,
       85,  237,   73,   73,   50,   73,  107,  104,   62,   74,
      235,   74,   74,   71,  231,  106,   73,   73,   76,   76,
       74,  107,   73,   74,   74,   75,  111,   75,  111,   85,
       75,   75,  106,  110,   74,   76,   78,  115,   78,   78,
       74,  110,  230,   76,  124,  124,  217,   78,   74,  217,
       78,   78,  115,  115,  118,  229,  118,  125,  125,  118,

      118,   78,  119,  119,  120,  232,  120,   78,  232,  120,
      120,  119,  119,  222,  119,   78,  123,  123,  126,  126,
      133,  133,  159,  159,  219,  119,  119,  160,  160,  162,
      162,  119,  161,  123,  161,  126,  218,  161,  161,  163,
      163,  123,  216,  126,  164,  164,  194,  194,  214,  163,
      213,  163,  195,  195,  234,  211,  210,  234,  209,  208,
      207,  164,  195,  163,  195,  206,  204,  203,  163,  164,
      201,  200,  199,  198,  193,  192,  195,  191,  189,  188,
      187,  195,  246,  246,  246,  246,  246,  247,  247,  186,
      247,  247,  248,  248,  250,  185,  250,  250,  250,  251,

      251,  251,  251,  251,  184,  183,  182,  181,  180,  179,
      176,  175,  172,  171,  170,  169,  166,  158,  157,  156,
      155,  154,  153,  152,  151,  150,  149,  148,  147,  146,
      145,  144,  143,  141,  139,  138,  137,  136,  135,  134,
      132,  131,  130,  129,  112,  109,  108,  105,  103,  102,
      100,   99,   98,   97,   96,   95,   94,   93,   92,   91,
       90,   89,   88,   86,   83,   79,   70,   57,   48,   47,
       46,   45,   43,   42,   40,   35,   34,   33,   26,   20,
       15,   12,   10,    9,    7,    3,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/c_lexer.lex"
#line 3 "src/c_lexer.lex"

#include <cstdio>
#include <cstdlib>

#include <string>
#include <iostream>
#include <vector>

#include "ast/Node.hpp"
#include "ast/Expression.hpp"

#include "c_parser.tab.hpp"


std::string consume_until_whitespace(char);
void preprocessor_line(const char*);
char parse_char_literal(const char* text);
char* parse_string_literal(const char* text);

void yyerror (char const *s);

int currLine = 1;
std::string currentSourceFile = "";
int currentSourceLine = 1;


struct TokenEntry {
	std::string TokenText;
	std::string TokenClass;
	std::string TokenType;
	int LineNum;
	std::string SourceFile;
	int SourceLine;

	TokenEntry(std::string text, std::string tkclass, std::string type) :
		TokenText(text),
		TokenClass(tkclass),
		TokenType(type),
		LineNum(currLine),
		SourceFile(currentSourceFile),
		SourceLine(currentSourceLine)
	{
	}

	void out() {
		fprintf(yyout, "%-20s %-14s %-16s %3d  %-14s %3d\n", TokenText.c_str(), TokenClass.c_str(), TokenType.c_str(), LineNum, SourceFile.c_str(), SourceLine);
	}
};

std::vector<TokenEntry> token_list;

/* ********************* Definitions ********************* */
/* ************************ Rules ************************ */
#line 692 "src/c_lexer.yy.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 77 "src/c_lexer.lex"


#line 877 "src/c_lexer.yy.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 246 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 387 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 79 "src/c_lexer.lex"
{ } /* ignore whitespace */
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 80 "src/c_lexer.lex"
{ currLine++; currentSourceLine++; yylineno++; } /* keep track of line numbers */
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 82 "src/c_lexer.lex"
{ preprocessor_line(yytext); } /* preprocessor line indicators */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 84 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "TVoid")); return TVOID; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "TLong")); return TLONG; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 86 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "TShort")); return TSHORT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 87 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "TChar")); return TCHAR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "TInt")); return TINT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 89 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "TFloat")); return TFLOAT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 90 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "TDouble")); return TDOUBLE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 92 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Auto")); return AUTO; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 93 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Const")); return CONST; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 94 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Extern")); return EXTERN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 95 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Register")); return REGISTER; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 96 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Static")); return STATIC; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 97 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Volatile")); return VOLATILE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 98 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Unsigned")); return UNSIGNED; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 99 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Signed")); return SIGNED; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 101 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Struct")); return STRUCT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 102 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Typedef")); return TYPEDEF; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 103 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Union")); return UNION; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 104 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Enum")); return ENUM; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 106 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "If")); return IF; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 107 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Else")); return ELSE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 108 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "While")); return WHILE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 109 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Do")); return DO; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 110 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "For")); return FOR; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 112 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Goto")); return GOTO; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 113 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Break")); return BREAK; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 114 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Continue")); return CONTINUE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 115 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Return")); return RETURN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 117 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Switch")); return SWITCH; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 118 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Case")); return CASE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 119 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Keyword", "Default")); return DEFAULT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 121 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "SizeOf")); return SIZEOF; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 123 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Dot")); return '.'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 124 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Arrow")); return ARROW; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 125 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Comma")); return ','; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 126 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Semicolon")); return ';'; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 127 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Ellipsis")); return ELLIPSIS; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 128 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "OpenParenthesis")); return '('; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 129 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "CloseParenthesis")); return ')'; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 130 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "OpenBracket")); return '['; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 131 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "CloseBracket")); return ']'; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 132 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "OpenBrace")); return OPENBRACE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 133 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "CloseBrace")); return CLOSEBRACE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 135 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Plus")); return '+'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 136 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Minus")); return '-'; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 137 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Star")); return '*'; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 138 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Slash")); return '/'; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 139 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Modulo")); return '%'; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 140 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Increment")); return INCREMENT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 141 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Decrement")); return DECREMENT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 143 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "LogicalNot")); return '!'; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 144 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "LogicalAnd")); return LOGICALAND; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 145 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "LogicalOr")); return LOGICALOR; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 147 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Ampersand")); return '&'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 148 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Pipe")); return '|'; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 149 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Caret")); return '^'; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 150 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Tilde")); return '~'; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 151 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "ShiftLeft")); return SHIFTLEFT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 152 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "ShiftRight")); return SHIFTRIGHT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 154 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Question")); return '?'; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 155 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Colon")); return ':'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 157 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Assign")); return '='; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 158 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "AssignPlus")); return ASSIGNPLUS; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 159 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "AssignMinus")); return ASSIGNMINUS; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 160 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "AssignStar")); return ASSIGNSTAR; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 161 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "AssignSlash")); return ASSIGNSLASH; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 162 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "AssignModulo")); return ASSIGNMODULO; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 163 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "AssignAmpersand")); return ASSIGNAMPERSAND; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 164 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "AssignPipe")); return ASSIGNPIPE; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 165 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "AssignCaret")); return ASSIGNCARET; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 166 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "AssignLeftShift")); return ASSIGNLEFTSHIFT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 167 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "AssignRightShift")); return ASSIGNRIGHTSHIFT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 169 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "LessThan")); return '<'; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 170 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "GreaterThan")); return '>'; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 171 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "Equals")); return EQUALS; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 172 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "NotEquals")); return NOTEQUALS; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 173 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "LessOrEqual")); return LESSOREQUAL; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 174 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Operator", "MoreOrEqual")); return MOREOREQUAL; }
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 176 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Constant", "CharLiteral"));
					yylval.c = parse_char_literal(yytext);
					return CHARLITERAL; }
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 180 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "StringLiteral", "StringLiteral"));
					yylval.s = parse_string_literal(yytext);
					return STRINGLITERAL; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 184 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Constant", "OctInt"));
					for(char* textbuf = yytext; *textbuf; textbuf++) {
						if(*textbuf == '8' || *textbuf == '9') {
							yyerror("syntax error: octal literals only allow digits from 0 to 7");
						}
					}
					yylval.i = strtol(yytext, NULL, 8);
					return OCTINT; } /* must be before decimal int! */
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 193 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Constant", "DecInt"));
					yylval.i = atoi(yytext);
					return DECINT; } /* must be after octal int! */
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 197 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Constant", "HexInt"));
					yylval.i = strtol(yytext, NULL, 16);
					return HEXINT; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 201 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Constant", "FloatingPoint"));
					yylval.d = atof(yytext);
					return FLOATINGDOUBLE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 205 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Constant", "FloatingPoint"));
					yylval.f = atof(yytext);
					return FLOATINGPOINT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 209 "src/c_lexer.lex"
{ token_list.push_back(TokenEntry(yytext, "Identifier", "Identifier"));
					yylval.s = strdup(yytext);
					return IDENTIFIER; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 213 "src/c_lexer.lex"
{
						std::string val = consume_until_whitespace(*yytext);
						token_list.push_back(TokenEntry(val, "Invalid", "Invalid"));
					} /* anything else is invalid */
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 218 "src/c_lexer.lex"
ECHO;
	YY_BREAK
#line 1443 "src/c_lexer.yy.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 246 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 246 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 245);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 218 "src/c_lexer.lex"



/* ********************* Subroutines ********************* */

std::string consume_until_whitespace(char first) {
	char c = 0;
	std::string s(1, first);

    while ((c = yyinput())) {
		if(c == ' ' || c == '\t' || c == '\r' || c == '\n')
			return s;
		s += c;
    }

	return s;
}

void preprocessor_line(const char* text) {
	// adjust context based on preprocessor line info
	// format: # linenum "filename" flags
	// flags: one or more of the following, separated by spaces
	// 1 : the start of a new file.
	// 2 : returning to a file (after having included another file).
	// 3 : that the following text comes from a system header file, so certain warnings should be suppressed.
	// 4 : that the following text should be treated as being wrapped in an implicit extern "C" block.

	std::string linenum;
	std::string sourcefile;
	bool f_newfile = false;
	bool f_returnfile = false;
	bool f_sysheader = false;
	bool f_externc = false;

	// first character is a hash
	++text;

	// second character is a space
	++text;

	// begin line number until space
	while(char c = *(text++)) {
		if(c == ' ')
			break;
		linenum += c;
	}

	// now there is a double quote
	++text;

	// begin file name until next double quote
	// stupid preprocessor allowing escaped quotes in name...
	bool escape_sequence = false;
	while(char c = *(text++)) {
		if(c == '\\') { // backslash
			if(escape_sequence) {
				escape_sequence = false;
				sourcefile += '\\';
			} else {
				escape_sequence = true;
			}
		} else if(c == '"') { // double quote
			if(escape_sequence) {
				escape_sequence = false;
				sourcefile += '"';
			} else {
				break;
			}
		} else {
			if(escape_sequence) { // other escape sequence
				escape_sequence = false;
				sourcefile += '\\';
			}
			sourcefile += c;
		}
	}

	// now there is a space, followed by flags
	while(char c = *(text++)) {
		if(c == '1') {
			f_newfile = true;
		} else if(c == '2') {
			f_returnfile = true;
		} else if(c == '3') {
			f_sysheader = true;
		} else if(c == '4') {
			f_externc = true;
		}
	}

	currentSourceFile = sourcefile;
	currentSourceLine = atoi(linenum.c_str());
	currLine++;
}

char parse_escape_sequence(const char*& str) {

	// iterate through text as a FSM
	char c;
	bool octal = false;
	bool hex = false;
	unsigned int tmp = 0;

	while((c = *str++)) {
		if(octal || hex) {
			if(octal && (c < '0' || c > '7')) { // end of escape sequence
				--str;
				if(tmp > 255) {
					yyerror("syntax error: octal escape sequence in literal overflowed");
				}
				unsigned char tmpc = (unsigned char) tmp;
				return *((char*) &tmpc);
			} else if(hex && !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F'))) { // end of escape sequence
				--str;
				if(tmp > 255) {
					yyerror("syntax error: hex escape sequence in literal overflowed");
				}
				unsigned char tmpc = (unsigned char) tmp;
				return *((char*) &tmpc);
			} else {
				// figure out the value of the digit
				unsigned char v = 0;
				if(c >= '0' && c <= '9') {
					v = c - '0';
				} else if(c >= 'a' && c <= 'f') {
					v = c - 'a';
				} else if(c >= 'A' && c <= 'F') {
					v = c - 'A';
				}
				// add digit to the temporary accumulator
				if(octal) {
					tmp = tmp * 8 + v;
				} else {
					tmp = tmp * 16 + v;
				}
			}
		} else if(c == '\\') {
			return '\\';
		} else if(c == '\'') {
			return '\'';
		} else if(c == 'n') {
			return '\n';
		} else if(c == '"') {
			return '"';
		} else if(c == '?') {
			return '?';
		} else if(c == 'r') {
			return '\r';
		} else if(c == 't') {
			return '\t';
		} else if(c == 'a') {
			return '\a';
		} else if(c == 'b') {
			return '\b';
		} else if(c == 'f') {
			return '\f';
		} else if(c == 'v') {
			return '\v';
		} else if(c == 'x') {
			hex = true;
		} else if(c >= '0' && c <= '7') {
			octal = true;
			tmp = c - '0';
		} else {
			yyerror("syntax error: invalid escape sequence in literal");
		}
	}
	yyerror("syntax error: invalid escape sequence in literal");
	return 0;
}

char parse_char_literal(const char* text) {
	// ignore L prefix
	if(*text == 'L') {
		++text;
	}

	// skip opening single quote
	++text;

	if(*text == '\\') {
		char c = parse_escape_sequence(++text);
		if(*text != '\'') { // there's still stuff in the string
			yyerror("syntax error: invalid escape sequence in character literal");
		}
		return c;
	} else {
		if(*(text+1) != '\'') {
			yyerror("syntax error: character literal too long");
		}
		return *text;
	}
}


char* parse_string_literal(const char* text) {
	// ignore L prefix
	if(*text == 'L') {
		++text;
	}

	// skip opening double quotes
	++text;

	// iterate through the string
	std::string buf;
	char c;
	while((c = *text++)) {
		if(c == '"') {
			break;
		} else if(c == '\\') {
			buf += parse_escape_sequence(text);
		} else {
			buf += c;
		}
	}

	return strdup(buf.c_str());
};


void yyerror (char const *s) {
	if(currentSourceFile != "") {\
		fprintf(stderr, "%s:%d: %s\n", currentSourceFile.c_str(), currentSourceLine, s);
	} else {
		fprintf(stderr, "line %d: %s\n", currLine, s);
	}
	exit(1);
}

/* ******************* Public functions ******************* */

void print_tokens() {
	fprintf(yyout, "Token text           Class          Type            Line  Source file   Line\n"
	"============================================================================\n");
	for(std::vector<TokenEntry>::iterator itr = token_list.begin(); itr != token_list.end(); ++itr) {
		(*itr).out();
	}
	fprintf(yyout, "\nTotal lines = %d\n", currLine);
}

